general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/dotfiles/alacritty/themes/themes/gruvbox_dark.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[font]
normal = { family = "RobotoMono Nerd Font", style = "Bold" }
size = 12

[window]
decorations = "None"
opacity = 0.85

[cursor]
style = { shape = "Block", blinking = "Never" }
